### ISSUE TITLE
SSL not setup correctly

### ISSUE THREAD

**Issue by zbuchalski** [jeansch/ciqw#2]
I was following the instruction and this is what I got. 
I haven't found any .Garmin folder nor .config/ciqw. 
Done in the virtualenv . 

I suspect that the instruction might need some additional prerequisites. 

(garmin_dev) MacBook-Pro:garmin zbuchalski$ pip install ciqw
Collecting ciqw
  Using cached ciqw-0.4.2.tar.gz (7.2 kB)
Collecting inotify
  Using cached inotify-0.2.10-py3-none-any.whl
Collecting requests
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting pyquery
  Using cached pyquery-1.4.3-py3-none-any.whl (22 kB)
Collecting nose
  Using cached nose-1.3.7-py3-none-any.whl (154 kB)
Collecting lxml>=2.1
  Using cached lxml-4.6.3-cp37-cp37m-macosx_10_9_x86_64.whl (4.5 MB)
Collecting cssselect>0.7.9
  Using cached cssselect-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting chardet<5,>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Building wheels for collected packages: ciqw
  Building wheel for ciqw (setup.py) ... done
  Created wheel for ciqw: filename=ciqw-0.4.2-py3-none-any.whl size=11249 sha256=c6be7d35957b70a9f89760735fd1347650bf571003f0adbf9ed90f24d8d8a9c7
  Stored in directory: /Users/zbuchalski/Library/Caches/pip/wheels/09/46/95/d434b74f7234725358a4520d9e0b7669c8e388f7dd5640ed1e
Successfully built ciqw
Installing collected packages: urllib3, nose, lxml, idna, cssselect, chardet, certifi, requests, pyquery, inotify, ciqw
Successfully installed certifi-2020.12.5 chardet-4.0.0 ciqw-0.4.2 cssselect-1.1.0 idna-2.10 inotify-0.2.10 lxml-4.6.3 nose-1.3.7 pyquery-1.4.3 requests-2.25.1 urllib3-1.26.4
(garmin_dev) MacBook-Pro:garmin zbuchalski$ ciqw-install-sdkmanager
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1414, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zbuchalski/dane/inwestycje/garmin/garmin_dev/bin/ciqw-install-sdkmanager", line 8, in <module>
    sys.exit(install_sdkmanager())
  File "/Users/zbuchalski/dane/inwestycje/garmin/garmin_dev/lib/python3.7/site-packages/ciqw/sdks.py", line 90, in install_sdkmanager
    DEVCIQ + 'sdk-manager/' + 'sdk-manager.json').read())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)>

**Comment by jeansch** [comment]
Disabled SSL verification on OSX.
